import { type ReactNode } from 'react'
import { Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Typography } from '@mui/material'
export function PageHeading({ eyebrow, title, subtitle, action }: { eyebrow: string; title: string; subtitle: string; action?: ReactNode }) { return <Box display="flex" justifyContent="space-between" alignItems="flex-end" gap={2} flexWrap="wrap" sx={{ mb: 3.5 }}><Box><Typography className="eyebrow">{eyebrow}</Typography><Typography variant="h4" sx={{ fontSize: { xs: 25, sm: 30 }, letterSpacing: '-1.1px', mt: .5 }}>{title}</Typography><Typography color="text.secondary" fontSize={13} sx={{ mt: .8 }}>{subtitle}</Typography></Box>{action}</Box> }
export function Tag({ children, tone = 'neutral' }: { children: ReactNode; tone?: 'neutral' | 'success' | 'info' | 'warning' }) { return <Chip label={children} size="small" sx={{ bgcolor: tone === 'success' ? 'success.main' : tone === 'info' ? 'info.light' : tone === 'warning' ? 'warning.light' : 'action.hover', color: tone === 'success' ? 'success.contrastText' : tone === 'info' ? 'info.dark' : tone === 'warning' ? 'warning.dark' : 'text.secondary', height: 24, fontSize: 11 }}/ > }
// Standard pop-up rule: a data-entry pop-up closes ONLY via its Cancel button (or after a successful save/import).
// Backdrop clicks and the Escape key are deliberately ignored, so no onClose is passed to the MUI Dialog.
export function FormDialog({ open, title, subtitle, onClose, onSubmit, busy, children, submitLabel = 'Save changes', maxWidth = 'sm', submitDisabled = false }: { open: boolean; title: string; subtitle?: string; onClose: () => void; onSubmit: () => void; busy?: boolean; children: ReactNode; submitLabel?: string; maxWidth?: 'xs' | 'sm' | 'md' | 'lg' | 'xl'; submitDisabled?: boolean }) { return <Dialog open={open} disableEscapeKeyDown fullWidth maxWidth={maxWidth}><DialogTitle sx={{ px: 3, pt: 3, pb: 1 }}><Box display="flex" justifyContent="space-between" alignItems="start"><Box><Typography variant="h6" fontSize={19}>{title}</Typography>{subtitle && <Typography fontSize={12} color="text.secondary" mt={.7}>{subtitle}</Typography>}</Box></Box></DialogTitle><DialogContent sx={{ px: 3, pt: '20px !important' }}>{children}</DialogContent><DialogActions sx={{ px: 3, pb: 3, pt: 1 }}><Button onClick={onClose} color="inherit">Cancel</Button><Button onClick={onSubmit} variant="contained" disabled={busy || submitDisabled}>{busy ? 'Saving...' : submitLabel}</Button></DialogActions></Dialog> }
export function ErrorMessage({ message }: { message: string }) { return message ? <Typography role="alert" color="error" fontSize={12} sx={{ mt: 1.5 }}>{message}</Typography> : null }
// Same rule as FormDialog for panels that are not a single submit form (attachments,
// revision history): no backdrop or Escape close, no close icon, footer button only.
export function PanelDialog({ open, title, subtitle, onClose, footer, children, maxWidth = 'md' }: { open: boolean; title: string; subtitle?: string; onClose: () => void; footer?: ReactNode; children: ReactNode; maxWidth?: 'sm' | 'md' | 'lg' }) { return <Dialog open={open} disableEscapeKeyDown fullWidth maxWidth={maxWidth}><DialogTitle sx={{ px: 3, pt: 3, pb: 1 }}><Typography variant="h6" fontSize={19}>{title}</Typography>{subtitle && <Typography fontSize={12} color="text.secondary" mt={.7}>{subtitle}</Typography>}</DialogTitle><DialogContent sx={{ px: 3, pt: '16px !important' }}>{children}</DialogContent><DialogActions sx={{ px: 3, pb: 3, pt: 1 }}>{footer ?? <Button onClick={onClose} color="inherit">Close</Button>}</DialogActions></Dialog> }
