import { Box, Divider, MenuItem, TextField, Typography } from '@mui/material'
import { ErrorMessage, FormDialog } from './Common'
import { SERVICE_CATEGORIES, SERVICE_PROVIDER_TYPES, serviceFormToPayload, type ServiceFormState, type ServicePayload } from '../lib/serviceMaster'
import type { VendorOption } from '../lib/vendorMaster'

function SectionTitle({ children }: { children: React.ReactNode }) {
  return <Typography fontSize={11} fontWeight={800} letterSpacing={1.1} color="text.secondary" textTransform="uppercase">{children}</Typography>
}

// Service codes are server-generated and immutable. The provider choice controls
// whether a workspace vendor can be selected; the API remains authoritative.
export function ServiceFormDialog({ open, title, subtitle, form, setForm, vendors, busy, error, onClose, onSubmit }: {
  open: boolean
  title: string
  subtitle: string
  form: ServiceFormState
  setForm: (patch: Partial<ServiceFormState>) => void
  vendors: VendorOption[]
  busy: boolean
  error: string
  onClose: () => void
  onSubmit: (payload: ServicePayload) => void
}) {
  const needsVendor = form.provider_type === 'Third Party Services'
  const hasCurrentVendorOption = vendors.some(vendor => vendor.id === form.vendor_id)

  return <FormDialog
    open={open}
    title={title}
    subtitle={subtitle}
    onClose={onClose}
    onSubmit={() => onSubmit(serviceFormToPayload(form))}
    busy={busy}
    submitLabel={title.startsWith('Edit') ? 'Save changes' : 'Create service'}
  >
    <Box display="grid" gap={2} pt={.5}>
      <SectionTitle>Service details</SectionTitle>
      <TextField
        label="Service code"
        value={form.service_code || 'Generated automatically on save'}
        fullWidth
        disabled
        helperText="Generated by the workspace and cannot be changed."
      />
      <TextField
        label="Service name"
        required
        fullWidth
        value={form.service_name}
        onChange={event => setForm({ service_name: event.target.value })}
        inputProps={{ maxLength: 200 }}
      />
      <Box display="grid" gap={2} gridTemplateColumns={{ xs: '1fr', sm: '1fr 1fr' }}>
        <TextField
          select
          label="Service category"
          required
          fullWidth
          value={form.service_category}
          onChange={event => setForm({ service_category: event.target.value as ServiceFormState['service_category'] })}
          helperText="Choose the drilling or completion service catalogue."
        >
          {SERVICE_CATEGORIES.map(category => <MenuItem key={category} value={category}>{category}</MenuItem>)}
        </TextField>
        <TextField
          select
          label="Provider type"
          required
          fullWidth
          value={form.provider_type}
          onChange={event => {
            const providerType = event.target.value as ServiceFormState['provider_type']
            setForm({ provider_type: providerType, ...(providerType === 'In House Services' ? { vendor_id: '' } : {}) })
          }}
          helperText="Set whether the service is delivered in house or by a third party."
        >
          {SERVICE_PROVIDER_TYPES.map(providerType => <MenuItem key={providerType} value={providerType}>{providerType}</MenuItem>)}
        </TextField>
      </Box>

      <Divider/>
      <SectionTitle>Service provider</SectionTitle>
      <TextField
        select
        label="Vendor / service provider"
        required={needsVendor}
        fullWidth
        value={form.vendor_id}
        disabled={!needsVendor || busy}
        error={needsVendor && !form.vendor_id}
        onChange={event => setForm({ vendor_id: event.target.value })}
        helperText={needsVendor
          ? 'Required for Third Party Services. Deleted vendors must be restored before use.'
          : 'Only applicable to Third Party Services.'}
      >
        <MenuItem value="">{needsVendor ? 'Select a vendor' : 'Not applicable for In House Services'}</MenuItem>
        {form.vendor_id && !hasCurrentVendorOption && <MenuItem value={form.vendor_id} disabled>Previously linked vendor — restore or replace it</MenuItem>}
        {vendors.map(vendor => <MenuItem key={vendor.id} value={vendor.id}>
          {vendor.label}{vendor.status !== 'active' ? ` · ${vendor.status}` : ''}
        </MenuItem>)}
      </TextField>
      <TextField
        label="Description"
        fullWidth
        multiline
        minRows={3}
        value={form.description}
        onChange={event => setForm({ description: event.target.value })}
        helperText="Scope, service notes, or internal guidance."
        inputProps={{ maxLength: 500 }}
      />
      <ErrorMessage message={error}/>
    </Box>
  </FormDialog>
}
