#!/usr/bin/env python3
"""Graphify the repo's local imports into a committed Graphviz DOT architecture map.

No service, token, third-party binary, or network needed. Run: python3 .agent/tools/graphify.py
Render optionally with Graphviz: dot -Tsvg .agent/memory/architecture.dot -o /tmp/architecture.svg
"""
import ast
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / ".agent/memory/architecture.dot"
EXTENSIONS = {".py", ".ts", ".tsx"}
EXCLUDE = {"node_modules", ".venv", "dist", "__pycache__", "tests", "alembic"}


def path_label(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def imports(path: Path) -> set[str]:
    text = path.read_text(encoding="utf-8")
    if path.suffix == ".py":
        try:
            tree = ast.parse(text)
        except SyntaxError:
            return set()
        names = set()
        for node in ast.walk(tree):
            if isinstance(node, ast.ImportFrom) and node.module and node.module.startswith("app."):
                names.add(node.module)
            elif isinstance(node, ast.Import):
                names.update(n.name for n in node.names if n.name.startswith("app."))
        return names
    return set(re.findall(r"(?:from\s+|import\s*\()['\"](\.{1,2}/[^'\"]+)", text))


def main() -> None:
    files = sorted(path for path in ROOT.rglob("*") if path.suffix in EXTENSIONS and not any(part in EXCLUDE for part in path.relative_to(ROOT).parts))
    labels = {path_label(path): path for path in files}
    edges = set()
    for label, path in labels.items():
        for name in imports(path):
            if name.startswith("app."):
                target = f"backend/{name.replace('.', '/')}.py"
                if target not in labels:
                    target = f"backend/{name.replace('.', '/')}/__init__.py"
            else:
                resolved = (path.parent / name).resolve()
                target = next((path_label(candidate) for suffix in (".tsx", ".ts", "/index.tsx", "/index.ts") if (candidate := Path(str(resolved) + suffix)).exists()), "")
            if target in labels and target != label:
                edges.add((label, target))
    lines = ['// Generated by .agent/tools/graphify.py; regenerate after architecture changes.', 'digraph WellCostingPro {', '  rankdir=LR;', '  graph [fontname="Helvetica", bgcolor="transparent"];', '  node [shape=box, style="rounded,filled", fillcolor="#e7f5f1", color="#2a8c80", fontname="Helvetica", fontsize=10];']
    for label in labels:
        lines.append(f'  "{label}";')
    for source, target in sorted(edges):
        lines.append(f'  "{source}" -> "{target}";')
    lines.append('}')
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Graphified {len(labels)} files and {len(edges)} imports into {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
