"""Declarative definitions of the priced catalogue types.

One ``PricedSpec`` per module. The generic router in ``app/api/catalogue_items.py``
and the shared rules in ``app/services/catalogue.py`` read these, so adding a
field or a new priced type means editing this file rather than copying routes.
"""

from app.models.catalogue import (
    CementAdditive,
    CementAdditiveRevision,
    DrillBit,
    DrillBitRevision,
    FUEL_TYPE_SEEDS,
    FuelPriceRevision,
    FuelType,
    MudChemical,
    MudChemicalRevision,
    TANGIBLE_SCOPES,
    Tangible,
    TangibleRevision,
)
from app.schemas.catalogue import (
    CementAdditiveCreate,
    CementAdditiveOut,
    CementAdditiveUpdate,
    DrillBitCreate,
    DrillBitOut,
    DrillBitUpdate,
    FuelOut,
    FuelRevise,
    MudChemicalCreate,
    MudChemicalOut,
    MudChemicalUpdate,
    TangibleCreate,
    TangibleOut,
    TangibleUpdate,
    UnitRevise,
    UpliftRevise,
)
from app.services.catalogue import (
    ChoiceField,
    OptionField,
    PricedSpec,
    TextField,
    seed_fixed_records,
)


def _seed_fuel(db, organization_id: str) -> None:
    seed_fixed_records(
        db,
        organization_id,
        model=FuelType,
        code_attr="fuel_code",
        name_attr="fuel_name",
        seeds=FUEL_TYPE_SEEDS,
        uom="L",
    )


TANGIBLES = PricedSpec(
    key="tangibles",
    label="Tangibles",
    item_type="Tangible",
    entity="tangible",
    model=Tangible,
    revision_model=TangibleRevision,
    revision_fk="tangible_id",
    revisions_attr="revisions",
    code_attr="tangible_code",
    name_attr="tangible_name",
    code_label="Tangible code",
    name_label="Tangible name",
    priced="uplift",
    options=(
        OptionField("category_id", "category", "tangible_category", "Category"),
        OptionField("subcategory_id", "subcategory", "tangible_subcategory", "Subcategory", parent_attr="category_id"),
        OptionField("manufacturer_id", "manufacturer", "manufacturer", "Manufacturer"),
    ),
    texts=(
        TextField("uom", "Unit of measure", 50),
        TextField("remarks", "Remarks", 500),
    ),
    choices=(ChoiceField("scope", "Scope", TANGIBLE_SCOPES),),
    duplicate_rule="relaxed",
    breakdown_attr="category_id",
    breakdown_label="Category",
    create_model=TangibleCreate,
    update_model=TangibleUpdate,
    revise_model=UpliftRevise,
    out_model=TangibleOut,
    import_required=(
        "tangible_code", "tangible_name", "scope", "category", "subcategory", "manufacturer", "unit_rate", "currency",
    ),
    import_optional=("uom", "po_number", "cost_uplift", "effective_date", "description", "remarks"),
    import_aliases={
        "tangible_code": ("code",),
        "tangible_name": ("name", "tangible"),
        "scope": ("tangible_scope",),
        "unit_rate": ("rate_as_per_po", "unit_rate_po", "rate_po"),
        "cost_uplift": ("uplift_percent", "uplift_pct"),
    },
    sample_row={
        "tangible_code": "TNG-0001",
        "tangible_name": "Casing centraliser 9-5/8in",
        "scope": "Drilling",
        "category": "Casing Accessories",
        "subcategory": "Centralisers",
        "manufacturer": "Weatherford",
        "uom": "EA",
        "po_number": "PO-4500123",
        "unit_rate": "1250",
        "cost_uplift": "100",
        "currency": "USD",
        "effective_date": "2026-01-31",
        "description": "Bow spring centraliser",
        "remarks": "",
    },
)

DRILL_BITS = PricedSpec(
    key="drill-bits",
    label="Drill Bits",
    item_type="Drill bit",
    entity="drill_bit",
    model=DrillBit,
    revision_model=DrillBitRevision,
    revision_fk="drill_bit_id",
    revisions_attr="revisions",
    code_attr="bit_code",
    name_attr="bit_name",
    code_label="Bit code",
    name_label="Bit name",
    priced="uplift",
    options=(
        OptionField("bit_type_id", "bit_type", "drill_bit_type", "Bit type"),
        OptionField("manufacturer_id", "manufacturer", "manufacturer", "Manufacturer"),
    ),
    texts=(
        TextField("model_no", "Model no.", 100, required=True),
        TextField("size", "Size", 60, required=True),
        TextField("iadc_code", "IADC code", 20),
        TextField("serial_number", "Serial number", 100),
        TextField("remarks", "Remarks", 500),
    ),
    duplicate_rule="relaxed",
    unique_text_attr="serial_number",
    breakdown_attr="bit_type_id",
    breakdown_label="Bit type",
    create_model=DrillBitCreate,
    update_model=DrillBitUpdate,
    revise_model=UpliftRevise,
    out_model=DrillBitOut,
    import_required=("bit_code", "bit_name", "bit_type", "model_no", "size", "manufacturer", "unit_rate", "currency"),
    import_optional=("iadc_code", "serial_number", "po_number", "cost_uplift", "effective_date", "description", "remarks"),
    import_aliases={
        "bit_code": ("code",),
        "bit_name": ("name",),
        "model_no": ("model", "model_number"),
        "serial_number": ("serial", "serial_no"),
        "unit_rate": ("rate_as_per_po", "unit_rate_po", "rate_po"),
        "cost_uplift": ("uplift_percent", "uplift_pct"),
        "iadc_code": ("iadc",),
    },
    sample_row={
        "bit_code": "DB-0001",
        "bit_name": "PDC bit 8-1/2in",
        "bit_type": "PDC",
        "model_no": "M1365",
        "size": "8-1/2 in",
        "iadc_code": "M423",
        "serial_number": "SN-88421",
        "manufacturer": "Halliburton",
        "po_number": "PO-4500456",
        "unit_rate": "85000",
        "cost_uplift": "100",
        "currency": "USD",
        "effective_date": "2026-02-01",
        "description": "",
        "remarks": "",
    },
)

MUD_CHEMICALS = PricedSpec(
    key="mud-chemicals",
    label="Mud Chemicals",
    item_type="Mud chemical",
    entity="mud_chemical",
    model=MudChemical,
    revision_model=MudChemicalRevision,
    revision_fk="mud_chemical_id",
    revisions_attr="revisions",
    code_attr="chemical_code",
    name_attr="chemical_name",
    code_label="Chemical code",
    name_label="Chemical name",
    priced="unit",
    options=(
        OptionField("group_id", "group", "mud_chemical_group", "Group"),
        OptionField("manufacturer_id", "manufacturer", "manufacturer", "Manufacturer", required=False),
    ),
    texts=(
        TextField("part_number", "Part number", 100),
        TextField("uom", "Unit of measure", 50),
        TextField("remarks", "Remarks", 500),
    ),
    duplicate_rule="unique_name",
    breakdown_attr="group_id",
    breakdown_label="Group",
    create_model=MudChemicalCreate,
    update_model=MudChemicalUpdate,
    revise_model=UnitRevise,
    out_model=MudChemicalOut,
    import_required=("chemical_code", "chemical_name", "group", "unit_rate", "currency"),
    import_optional=("manufacturer", "part_number", "uom", "po_number", "effective_date", "description", "remarks"),
    import_aliases={
        "chemical_code": ("code",),
        "chemical_name": ("name", "chemical"),
        "part_number": ("part_no", "part"),
        "unit_rate": ("rate", "rate_as_per_po", "unit_rate_po"),
        "group": ("mud_chemical_group", "chemical_group"),
    },
    sample_row={
        "chemical_code": "MC-0001",
        "chemical_name": "Barite",
        "group": "Weighting agent",
        "manufacturer": "Baroid",
        "part_number": "BR-25",
        "uom": "MT",
        "unit_rate": "420",
        "currency": "USD",
        "po_number": "",
        "effective_date": "2026-01-15",
        "description": "",
        "remarks": "",
    },
)

CEMENT_ADDITIVES = PricedSpec(
    key="cement-additives",
    label="Cement Additives",
    item_type="Cement additive",
    entity="cement_additive",
    model=CementAdditive,
    revision_model=CementAdditiveRevision,
    revision_fk="cement_additive_id",
    revisions_attr="revisions",
    code_attr="additive_code",
    name_attr="additive_name",
    code_label="Additive code",
    name_label="Additive name",
    priced="unit",
    options=(
        OptionField("additive_type_id", "additive_type", "cement_additive_type", "Additive type"),
        OptionField("manufacturer_id", "manufacturer", "manufacturer", "Manufacturer", required=False),
    ),
    texts=(
        TextField("part_number", "Part number", 100),
        TextField("uom", "Unit of measure", 50),
        TextField("remarks", "Remarks", 500),
    ),
    duplicate_rule="unique_name",
    breakdown_attr="additive_type_id",
    breakdown_label="Additive type",
    create_model=CementAdditiveCreate,
    update_model=CementAdditiveUpdate,
    revise_model=UnitRevise,
    out_model=CementAdditiveOut,
    import_required=("additive_code", "additive_name", "additive_type", "unit_rate", "currency"),
    import_optional=("manufacturer", "part_number", "uom", "po_number", "effective_date", "description", "remarks"),
    import_aliases={
        "additive_code": ("code",),
        "additive_name": ("name", "additive"),
        "part_number": ("part_no", "part"),
        "unit_rate": ("rate", "rate_as_per_po", "unit_rate_po"),
        "additive_type": ("type", "cement_additive_type"),
    },
    sample_row={
        "additive_code": "CA-0001",
        "additive_name": "Calcium chloride",
        "additive_type": "Accelerator",
        "manufacturer": "Halliburton",
        "part_number": "CC-50",
        "uom": "MT",
        "unit_rate": "610",
        "currency": "USD",
        "po_number": "",
        "effective_date": "2026-01-15",
        "description": "",
        "remarks": "",
    },
)

FUEL = PricedSpec(
    key="fuel-types",
    label="Fuel",
    item_type="Fuel",
    entity="fuel_type",
    model=FuelType,
    revision_model=FuelPriceRevision,
    revision_fk="fuel_type_id",
    revisions_attr="revisions",
    code_attr="fuel_code",
    name_attr="fuel_name",
    code_label="Fuel code",
    name_label="Fuel",
    priced="unit",
    duplicate_rule="none",
    lifecycle=False,
    revise_model=FuelRevise,
    out_model=FuelOut,
    seed=_seed_fuel,
)

PRICED_SPECS: dict[str, PricedSpec] = {spec.key: spec for spec in (TANGIBLES, DRILL_BITS, MUD_CHEMICALS, CEMENT_ADDITIVES, FUEL)}
